<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Droniverse.Community.Application\Droniverse.Community.Application.csproj" />
		<ProjectReference Include="..\Droniverse.Community.Domain\Droniverse.Community.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		
		<PackageReference Include="Hangfire" Version="1.8.23" />
		
		<PackageReference Include="Hangfire.MySqlStorage" Version="2.0.3" />
		
		<PackageReference Include="MySql.Data" Version="9.5.0" />

		<PackageReference Include="MySql.EntityFrameworkCore" Version="9.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MongoDB.EntityFrameworkCore" Version="9.0.3" />
	</ItemGroup>

</Project>
