apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-microservice
  namespace: droniverse-hostname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-microservice
  template:
    metadata:
      labels:
        app: academy-microservice
    spec:
      containers:
        - name: academy-microservice
          image: blackpro2k4/academy-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: academy-microservice
  namespace: droniverse-hostname
spec:
  selector:
    app: academy-microservice
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP