apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-microservice
  namespace: droniverse-hostname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-microservice
  template:
    metadata:
      labels:
        app: community-microservice
    spec:
      containers:
        - name: community-microservice
          image: blackpro2k4/community-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: community-microservice
  namespace: droniverse-hostname
spec:
  selector:
    app: community-microservice
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP