<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>af1fded8-45f1-45bd-93b1-cd261bc4ef7c</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DotNetEnv" Version="3.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="MMLib.SwaggerForOcelot" Version="9.0.0" />
		<PackageReference Include="Ocelot" Version="24.1.0" />
		<PackageReference Include="Ocelot.Provider.Polly" Version="24.1.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.23" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controllers\" />
		<ProjectReference Include="..\..\Droniverse.Shared\Droniverse.Shared.csproj" />
		<None Update="ocelot.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
