// <auto-generated />
using System;
using Droniverse.Community.Infrastructure.Persistence.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Droniverse.Community.Infrastructure.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20260123054342_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeNameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TypeNameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("ClubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubCode")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LimitClubManagers")
                        .HasColumnType("int");

                    b.Property<int>("LimitParticipation")
                        .HasColumnType("int");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("ClubID");

                    b.ToTable("Club", null, t =>
                        {
                            t.HasCheckConstraint("CK_Club_Status", "`Status` IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ClubCategory", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubID")
                        .HasColumnType("char(36)");

                    b.HasKey("CategoryID", "ClubID");

                    b.HasIndex("ClubID");

                    b.ToTable("ClubCategory", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ClubCourse", b =>
                {
                    b.Property<Guid>("ClubID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)");

                    b.HasKey("ClubID", "CourseID");

                    b.ToTable("ClubCourse", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ClubRequest", b =>
                {
                    b.Property<Guid>("ClubRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApproveID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RequestID")
                        .HasColumnType("char(36)");

                    b.HasKey("ClubRequestID");

                    b.HasIndex("ClubID");

                    b.ToTable("ClubRequest", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Competition", b =>
                {
                    b.Property<Guid>("CompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("CompetitionID");

                    b.HasIndex("ClubID");

                    b.ToTable("Competition", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.CompetitionCertificate", b =>
                {
                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CertificateID")
                        .HasColumnType("char(36)");

                    b.HasKey("CompetitionID", "CertificateID");

                    b.ToTable("CompetitionCertificate", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("MediaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MediaTypeID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("MediaID");

                    b.HasIndex("MediaTypeID");

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.MediaType", b =>
                {
                    b.Property<Guid>("MediaTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeNameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TypeNameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("MediaTypeID");

                    b.ToTable("MediaType", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Participation", b =>
                {
                    b.Property<Guid>("ParticipationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApproveID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<ulong>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("ParticipationID");

                    b.HasIndex("ClubID");

                    b.ToTable("Participation", null, t =>
                        {
                            t.HasCheckConstraint("CK_Participation_Status", "`Status` IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CodeID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("VND");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(14, 9)");

                    b.Property<string>("ProductNameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductNameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("ReferenceID")
                        .HasColumnType("char(36)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product", null, t =>
                        {
                            t.HasCheckConstraint("CK_Product_Currency", "`Currency` IN ('VND', 'USD')");

                            t.HasCheckConstraint("CK_Product_Status", "`Status` IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoryNameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CategoryNameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CategoryID");

                    b.ToTable("ProductCategory", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Round", b =>
                {
                    b.Property<Guid>("RoundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LabID")
                        .HasColumnType("char(36)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RoundID");

                    b.HasIndex("CompetitionID");

                    b.ToTable("Round", null, t =>
                        {
                            t.HasCheckConstraint("CK_Round_Status", "Status IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserCompetion", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserID", "CompetitionID");

                    b.HasIndex("CompetitionID");

                    b.ToTable("UserCompetion", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserProduct", b =>
                {
                    b.Property<Guid>("UserProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AcquiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("UserProduct", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserRound", b =>
                {
                    b.Property<Guid>("UserRoundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FeedbackEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedbackVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("Length")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfStep")
                        .HasColumnType("int");

                    b.Property<decimal>("Point")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("RoundID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Time")
                        .HasColumnType("float");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserRoundID");

                    b.HasIndex("RoundID");

                    b.ToTable("UserRound", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ClubCategory", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Category", "Category")
                        .WithMany("ClubCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Droniverse.Community.Domain.Entities.Club", "Club")
                        .WithMany("ClubCategories")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ClubCourse", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Club", "Club")
                        .WithMany("ClubCourses")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ClubRequest", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Club", "Club")
                        .WithMany("ClubRequests")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Competition", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Club", "Club")
                        .WithMany("Competitions")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.CompetitionCertificate", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Competition", "Competition")
                        .WithMany("CompetitionCertificates")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Media", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.MediaType", "MediaType")
                        .WithMany("Medias")
                        .HasForeignKey("MediaTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Participation", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Club", "Club")
                        .WithMany("Participations")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Product", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Round", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Competition", "Competition")
                        .WithMany("Rounds")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserCompetion", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Competition", "Competition")
                        .WithMany("UserCompetitions")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserProduct", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Product", "Product")
                        .WithMany("UserProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserRound", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Round", "Round")
                        .WithMany("UserRounds")
                        .HasForeignKey("RoundID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Category", b =>
                {
                    b.Navigation("ClubCategories");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Club", b =>
                {
                    b.Navigation("ClubCategories");

                    b.Navigation("ClubCourses");

                    b.Navigation("ClubRequests");

                    b.Navigation("Competitions");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Competition", b =>
                {
                    b.Navigation("CompetitionCertificates");

                    b.Navigation("Rounds");

                    b.Navigation("UserCompetitions");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.MediaType", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Product", b =>
                {
                    b.Navigation("UserProducts");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Round", b =>
                {
                    b.Navigation("UserRounds");
                });
#pragma warning restore 612, 618
        }
    }
}
