// <auto-generated />
using System;
using Droniverse.Community.Infrastructure.Persistence.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Droniverse.Community.Infrastructure.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20260421153629_Add_Table_WithdrawRequest")]
    partial class Add_Table_WithdrawRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CompetitionPrize", b =>
                {
                    b.Property<Guid>("CompetitionPrizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .HasColumnType("text");

                    b.Property<int>("RankFrom")
                        .HasColumnType("int");

                    b.Property<int>("RankTo")
                        .HasColumnType("int");

                    b.Property<sbyte>("RewardType")
                        .HasColumnType("tinyint");

                    b.Property<string>("RewardValueGiftEN")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RewardValueGiftVN")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("RewardValueMoney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TitleVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("CompetitionPrizeID");

                    b.HasIndex("CompetitionID");

                    b.ToTable("CompetitionPrize", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("ClubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClubCode")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<string>("ClubPolicyEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClubPolicyVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("DroneID")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("LimitClubManagers")
                        .HasColumnType("int");

                    b.Property<int>("LimitParticipation")
                        .HasColumnType("int");

                    b.Property<Guid>("ManagerID")
                        .HasColumnType("char(36)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("SuspendedReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ClubID");

                    b.ToTable("Club", null, t =>
                        {
                            t.HasCheckConstraint("CK_Club_Status", "`Status` IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ClubAttemptRequest", b =>
                {
                    b.Property<Guid>("ClubRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ApproverID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("MediaID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RequesterID")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ClubRequestID");

                    b.HasIndex("ClubID");

                    b.HasIndex("MediaID");

                    b.HasIndex("RequesterID");

                    b.HasIndex("Status");

                    b.ToTable("ClubAttemptRequest", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ClubCreationRequest", b =>
                {
                    b.Property<Guid>("ClubCreationRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ApproverID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ClubID")
                        .HasColumnType("char(36)");

                    b.Property<string>("ClubPolicyEN")
                        .HasColumnType("text");

                    b.Property<string>("ClubPolicyVN")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("DroneID")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("LimitClubManager")
                        .HasColumnType("int");

                    b.Property<int>("LimitParticipant")
                        .HasColumnType("int");

                    b.Property<Guid>("MediaID")
                        .HasColumnType("char(36)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("RequesterID")
                        .HasColumnType("char(36)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ClubCreationRequestID");

                    b.HasIndex("ClubID");

                    b.HasIndex("MediaID");

                    b.ToTable("ClubCreationRequest", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Competition", b =>
                {
                    b.Property<Guid>("CompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("InvalidAt")
                        .HasColumnType("datetime");

                    b.Property<string>("InvalidReason")
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsSummarized")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("RegistrationEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RegistrationStartDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ResultPublishedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RuleContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("VisibleAt")
                        .HasColumnType("datetime");

                    b.HasKey("CompetitionID");

                    b.HasIndex("ClubID");

                    b.ToTable("Competition", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.CompetitionCertificate", b =>
                {
                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CertificateID")
                        .HasColumnType("char(36)");

                    b.HasKey("CompetitionID", "CertificateID");

                    b.ToTable("CompetitionCertificate", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("MediaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<Guid>("MediaTypeID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MediaID");

                    b.HasIndex("MediaTypeID");

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.MediaType", b =>
                {
                    b.Property<Guid>("MediaTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeNameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TypeNameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("MediaTypeID");

                    b.ToTable("MediaType", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Participation", b =>
                {
                    b.Property<Guid>("ParticipationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ApproverID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LeftDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("ParticipationID");

                    b.HasIndex("ClubID");

                    b.ToTable("Participation", null, t =>
                        {
                            t.HasCheckConstraint("CK_Participation_Status", "`Status` IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("VND");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(20, 9)");

                    b.Property<string>("ProductNameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductNameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("ReferenceID")
                        .HasColumnType("char(36)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product", null, t =>
                        {
                            t.HasCheckConstraint("CK_Product_Currency", "`Currency` IN ('VND', 'USD')");

                            t.HasCheckConstraint("CK_Product_Status", "`Status` IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoryNameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CategoryNameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CategoryID");

                    b.ToTable("ProductCategory", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Round", b =>
                {
                    b.Property<Guid>("RoundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsSummarized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LabID")
                        .HasColumnType("char(36)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<TimeSpan>("TimeLimit")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("RoundID");

                    b.HasIndex("CompetitionID");

                    b.ToTable("Round", null, t =>
                        {
                            t.HasCheckConstraint("CK_Round_Status", "Status IN (0,1,2,3)");
                        });
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<Guid>("ReferenceID")
                        .HasColumnType("char(36)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("WalletID")
                        .HasColumnType("char(36)");

                    b.HasKey("TransactionID");

                    b.HasIndex("WalletID");

                    b.ToTable("Transaction", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Status", "Status IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Transaction_Type", "Type IN ('COMMISSION', 'WITHDRAWAL', 'REFUND')");
                        });
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserCompetition", b =>
                {
                    b.Property<Guid>("UserCompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("PrizeID")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserCompetitionID");

                    b.HasIndex("CompetitionID");

                    b.HasIndex("UserID");

                    b.ToTable("UserCompetition", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserPrize", b =>
                {
                    b.Property<Guid>("UserPrizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("userPrizeID");

                    b.Property<DateTime?>("AwardedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("awardedAt");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdAt");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("createdBy");

                    b.Property<bool>("IsAwarded")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isAwarded");

                    b.Property<Guid>("PrizeID")
                        .HasColumnType("char(36)")
                        .HasColumnName("prizeID");

                    b.Property<int>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("rank");

                    b.Property<int>("RewardType")
                        .HasColumnType("int")
                        .HasColumnName("rewardType");

                    b.Property<string>("RewardValueGiftEN")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rewardValueGiftEN");

                    b.Property<string>("RewardValueGiftVN")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rewardValueGiftVN");

                    b.Property<decimal?>("RewardValueMoney")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("rewardValueMoney");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedAt");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updatedBy");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .HasColumnName("userID");

                    b.HasKey("UserPrizeID");

                    b.HasIndex("CompetitionID");

                    b.HasIndex("PrizeID");

                    b.ToTable("UserPrize", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserProduct", b =>
                {
                    b.Property<Guid>("UserProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AcquiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("UserProduct", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("WalletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BankNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<Guid>("OwnerID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("WalletID");

                    b.ToTable("Wallet", (string)null);
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.WithdrawRequest", b =>
                {
                    b.Property<Guid>("WithdrawRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("ApproverID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("WalletID")
                        .HasColumnType("char(36)");

                    b.HasKey("WithdrawRequestID");

                    b.HasIndex("WalletID");

                    b.ToTable("WithdrawRequest", null, t =>
                        {
                            t.HasCheckConstraint("CK_WithdrawRequest_Status", "Status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELED')");
                        });
                });

            modelBuilder.Entity("UserRound", b =>
                {
                    b.Property<Guid>("UserRoundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan?>("ExecutionTime")
                        .HasColumnType("time");

                    b.Property<string>("FeedbackEN")
                        .HasColumnType("text");

                    b.Property<string>("FeedbackVN")
                        .HasColumnType("text");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsSequentialCheckpoints")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("NumberOfSteps")
                        .HasColumnType("int");

                    b.Property<float?>("PathLength")
                        .HasColumnType("float");

                    b.Property<decimal?>("Point")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("RoundID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Solution")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserRoundID");

                    b.HasIndex("RoundID");

                    b.ToTable("UserRound", (string)null);
                });

            modelBuilder.Entity("CompetitionPrize", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Competition", "Competition")
                        .WithMany("CompetitionPrizes")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ClubAttemptRequest", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Club", "Club")
                        .WithMany("ClubRequests")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Droniverse.Community.Domain.Entities.Media", "Media")
                        .WithMany("ClubAttemptRequests")
                        .HasForeignKey("MediaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Club");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ClubCreationRequest", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Droniverse.Community.Domain.Entities.Media", "Media")
                        .WithMany("ClubCreationRequests")
                        .HasForeignKey("MediaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Competition", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Club", "Club")
                        .WithMany("Competitions")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.CompetitionCertificate", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Competition", "Competition")
                        .WithMany("CompetitionCertificates")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Media", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.MediaType", "MediaType")
                        .WithMany("Medias")
                        .HasForeignKey("MediaTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Participation", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Club", "Club")
                        .WithMany("Participations")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Product", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Round", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Competition", "Competition")
                        .WithMany("Rounds")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserCompetition", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Competition", "Competition")
                        .WithMany("UserCompetitions")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserPrize", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Competition", "Competition")
                        .WithMany("UserPrizes")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompetitionPrize", "Prize")
                        .WithMany("UserPrizes")
                        .HasForeignKey("PrizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Prize");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.UserProduct", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Product", "Product")
                        .WithMany("UserProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.WithdrawRequest", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("UserRound", b =>
                {
                    b.HasOne("Droniverse.Community.Domain.Entities.Round", "Round")
                        .WithMany("UserRounds")
                        .HasForeignKey("RoundID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("CompetitionPrize", b =>
                {
                    b.Navigation("UserPrizes");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Club", b =>
                {
                    b.Navigation("ClubRequests");

                    b.Navigation("Competitions");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Competition", b =>
                {
                    b.Navigation("CompetitionCertificates");

                    b.Navigation("CompetitionPrizes");

                    b.Navigation("Rounds");

                    b.Navigation("UserCompetitions");

                    b.Navigation("UserPrizes");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Media", b =>
                {
                    b.Navigation("ClubAttemptRequests");

                    b.Navigation("ClubCreationRequests");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.MediaType", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Product", b =>
                {
                    b.Navigation("UserProducts");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Round", b =>
                {
                    b.Navigation("UserRounds");
                });

            modelBuilder.Entity("Droniverse.Community.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
