// <auto-generated />
using System;
using Droniverse.Academy.Infrastructure.Persistence.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Droniverse.Academy.Infrastructure.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20260425165439_Add_Assignment")]
    partial class Add_Assignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Certificate", b =>
                {
                    b.Property<Guid>("CertificateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CertificateNameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CertificateNameVN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CourseVersionID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.HasKey("CertificateID");

                    b.HasIndex("CourseVersionID")
                        .IsUnique();

                    b.ToTable("Certificate", (string)null);
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.HasKey("AssignmentID");

                    b.ToTable("Assignment", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assignment_EstimatedTime", "`EstimatedTime` >= 0");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Code", b =>
                {
                    b.Property<string>("CodeID")
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ClubID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("UsedByUserID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UsedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CodeID");

                    b.HasIndex("CourseID");

                    b.ToTable("Code", null, t =>
                        {
                            t.HasCheckConstraint("CK_Code_Status", "`Status` IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CurrentVersionID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DroneID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LevelID")
                        .HasColumnType("char(36)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("CourseID");

                    b.HasIndex("CurrentVersionID");

                    b.HasIndex("DroneID");

                    b.HasIndex("LevelID");

                    b.ToTable("Course", null, t =>
                        {
                            t.HasCheckConstraint("CK_Course_Status", "`Status` IN (0,1,2,3)");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.CourseVersion", b =>
                {
                    b.Property<Guid>("CourseVersionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangeLog")
                        .HasColumnType("text");

                    b.Property<string>("ContextEN")
                        .HasColumnType("text");

                    b.Property<string>("ContextVN")
                        .HasColumnType("text");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .HasColumnType("text");

                    b.Property<int?>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TitleVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("CourseVersionID");

                    b.HasIndex("CourseID", "Version")
                        .IsUnique();

                    b.ToTable("CourseVersion", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourseVersion_Status", "`Status` IN (0,1,2,3)");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Drone", b =>
                {
                    b.Property<Guid>("DroneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DroneNameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DroneNameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("DroneTypeID")
                        .HasColumnType("char(36)");

                    b.Property<float>("Height")
                        .HasColumnType("float");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("char(255)")
                        .HasColumnName("ImgURL");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<float>("Weight")
                        .HasColumnType("float");

                    b.HasKey("DroneID");

                    b.HasIndex("DroneTypeID");

                    b.ToTable("Drone", null, t =>
                        {
                            t.HasCheckConstraint("CK_Drone_Status", "`Status` IN (1,2,3)");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.DroneType", b =>
                {
                    b.Property<Guid>("DroneTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeNameEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TypeNameVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("DroneTypeID");

                    b.ToTable("DroneType", (string)null);
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseVersionID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EnrollDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastAccessDate")
                        .HasColumnType("datetime");

                    b.Property<float>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("CourseVersionID");

                    b.ToTable("Enrollment", null, t =>
                        {
                            t.HasCheckConstraint("CK_Enrollment_Status", "`Status` IN (0,1,2,3)");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CourseVersionID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<sbyte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("CourseVersionID");

                    b.ToTable("Feedback", null, t =>
                        {
                            t.HasCheckConstraint("CK_Feedback_Rating", "`Rating` BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Lab", b =>
                {
                    b.Property<Guid>("LabID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<sbyte>("Level")
                        .HasColumnType("tinyint");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.HasKey("LabID");

                    b.ToTable("Lab", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lab_Level", "`Level` IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Lab_Status", "`Status` IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_Lab_Type", "`Type` IN ('LEARNING', 'COMPETITION')");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ModuleID")
                        .HasColumnType("char(36)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("ReferenceID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("LessonID");

                    b.HasIndex("ModuleID", "OrderIndex")
                        .IsUnique();

                    b.ToTable("Lesson", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lesson_OrderIndex", "`OrderIndex` > 0");

                            t.HasCheckConstraint("CK_Lesson_Type", "`Type` IN ('THEORY', 'QUIZ', 'LAB', 'PHYSIC', 'LAB_PHYSIC', 'VR', 'ASSIGNMENT')");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Level", b =>
                {
                    b.Property<Guid>("LevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .HasColumnType("text");

                    b.Property<Guid>("DroneID")
                        .HasColumnType("char(36)");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LevelID");

                    b.HasIndex("DroneID", "LevelNumber")
                        .IsUnique();

                    b.ToTable("Level", null, t =>
                        {
                            t.HasCheckConstraint("CK_Level_LevelNumber", "`LevelNumber` IN (1,2,3,4)");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.LevelCourseRequirement", b =>
                {
                    b.Property<Guid>("LevelID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)");

                    b.HasKey("LevelID", "CourseID");

                    b.HasIndex("CourseID");

                    b.ToTable("LevelCourseRequirement", (string)null);
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseVersionID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<int>("ModuleNumber")
                        .HasColumnType("int");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TitleVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.HasKey("ModuleID");

                    b.HasIndex("CourseVersionID");

                    b.ToTable("Module", (string)null);
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.PrerequisiteCourse", b =>
                {
                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PrerequisiteCourseID")
                        .HasColumnType("char(36)");

                    b.HasKey("CourseID", "PrerequisiteCourseID");

                    b.HasIndex("PrerequisiteCourseID");

                    b.ToTable("PrerequisiteCourse", null, t =>
                        {
                            t.HasCheckConstraint("CK_PrerequisiteCourse_SelfReference", "`CourseID` <> `PrerequisiteCourseID`");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PassScore")
                        .HasColumnType("float");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("int");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TitleVN")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<float>("TotalScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.HasKey("QuizID");

                    b.ToTable("Quiz", (string)null);
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<Guid>("AttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsPassed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<Guid>("QuizID")
                        .HasColumnType("char(36)");

                    b.Property<float?>("Score")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("SubmitTime")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("AttemptID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizAttempt", (string)null);
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AnswerA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnswerA_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnswerB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnswerB_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnswerC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnswerC_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnswerD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnswerD_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<Guid>("QuizID")
                        .HasColumnType("char(36)");

                    b.Property<float>("Score")
                        .HasColumnType("float");

                    b.HasKey("QuestionID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizQuestion", null, t =>
                        {
                            t.HasCheckConstraint("CK_QuizQuestion_CorrectAnswer", "`CorrectAnswer` IN ('A','B','C','D')");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.QuizQuestionAttempt", b =>
                {
                    b.Property<Guid>("AttemptAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AttemptID")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<Guid>("QuestionID")
                        .HasColumnType("char(36)");

                    b.Property<float?>("Score")
                        .HasColumnType("float");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("AttemptAnswerID");

                    b.HasIndex("AttemptID");

                    b.HasIndex("QuestionID");

                    b.ToTable("QuizQuestionAttempt", null, t =>
                        {
                            t.HasCheckConstraint("CK_QuizQuestionAttempt_SelectedAnswer", "`SelectedAnswer` IN ('A','B','C','D')");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReferenceID")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResponseEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("ReportID");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Theory", b =>
                {
                    b.Property<Guid>("TheoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentEN")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContentVN")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TitleVN")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.HasKey("TheoryID");

                    b.ToTable("Theory", (string)null);
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserAssignment", b =>
                {
                    b.Property<Guid>("UserAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssignmentID")
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EnrollmentID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MediaID")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0);

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime");

                    b.HasKey("UserAssignmentID");

                    b.HasIndex("AssignmentID", "EnrollmentID", "AttemptNumber")
                        .IsUnique();

                    b.HasIndex("EnrollmentID", "Status", "SubmittedAt");

                    b.ToTable("UserAssignment", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserAssignment_AttemptNumber", "`AttemptNumber` >= 1");

                            t.HasCheckConstraint("CK_UserAssignment_ReviewRequiredOnFinalStatus", "(`Status` IN (2,3) AND `ReviewedBy` IS NOT NULL AND `ReviewedAt` IS NOT NULL AND `Score` IS NOT NULL) OR (`Status` IN (0,1))");

                            t.HasCheckConstraint("CK_UserAssignment_Score", "`Score` IS NULL OR (`Score` BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("CK_UserAssignment_Status", "`Status` IN (0,1,2,3)");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserCertificate", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CertificateID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AchievedDate")
                        .HasColumnType("date");

                    b.Property<string>("CertificateUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("UserID", "CertificateID");

                    b.HasIndex("CertificateID");

                    b.ToTable("UserCertificate", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserCertificate_Status", "`Status` IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserLab", b =>
                {
                    b.Property<Guid>("UserLabID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FeedbackEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedbackVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LabID")
                        .HasColumnType("char(36)");

                    b.Property<float>("Length")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfStep")
                        .HasColumnType("int");

                    b.Property<decimal>("Point")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Time")
                        .HasColumnType("float");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserLabID");

                    b.HasIndex("LabID");

                    b.ToTable("UserLab", (string)null);
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserLesson", b =>
                {
                    b.Property<Guid>("UserLessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastAccessDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("char(36)");

                    b.Property<float>("Progress")
                        .HasColumnType("float");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0);

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserLessonID");

                    b.HasIndex("LessonID");

                    b.ToTable("UserLesson", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserLesson_Progress", "`Progress` BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_UserLesson_Status", "`Status` IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserLevel", b =>
                {
                    b.Property<Guid>("UserLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AchievedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("LevelID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserLevelID");

                    b.HasIndex("LevelID");

                    b.HasIndex("UserID", "LevelID")
                        .IsUnique();

                    b.ToTable("UserLevel", (string)null);
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserModule", b =>
                {
                    b.Property<Guid>("UserModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ModuleID")
                        .HasColumnType("char(36)");

                    b.Property<float>("Progress")
                        .HasColumnType("float");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserModuleID");

                    b.HasIndex("ModuleID", "UserID");

                    b.ToTable("UserModule", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserModule_Progress", "`Progress` >= 0 AND `Progress` <= 100");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserSimulator", b =>
                {
                    b.Property<Guid>("UserSimulatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("FlightTime")
                        .HasColumnType("int");

                    b.Property<ulong>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmitAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserSimulatorID");

                    b.HasIndex("LessonID");

                    b.HasIndex("UserID", "LessonID");

                    b.ToTable("UserSimulator", (string)null);
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.VRSimulator", b =>
                {
                    b.Property<Guid>("VRSimulatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.HasKey("VRSimulatorID");

                    b.ToTable("VRSimulator", null, t =>
                        {
                            t.HasCheckConstraint("CK_VRSimulator_EstimatedTime", "`EstimatedTime` > 0");

                            t.HasCheckConstraint("CK_VRSimulator_Type", "`Type` IN ('LEARNING', 'COMPETITION')");
                        });
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.WebSimulator", b =>
                {
                    b.Property<Guid>("WebSimulatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("char(20)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DroneID")
                        .HasColumnType("char(36)");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<string>("ObjectivesEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ObjectivesVN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleVN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.HasKey("WebSimulatorID");

                    b.HasIndex("DroneID");

                    b.ToTable("WebSimulator", null, t =>
                        {
                            t.HasCheckConstraint("CK_WebSimulator_EstimatedTime", "`EstimatedTime` > 0");

                            t.HasCheckConstraint("CK_WebSimulator_Type", "`Type` IN ('PHYSIC', 'LAB_PHYSIC')");
                        });
                });

            modelBuilder.Entity("Certificate", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.CourseVersion", "CourseVersion")
                        .WithOne("Certificate")
                        .HasForeignKey("Certificate", "CourseVersionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseVersion");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Code", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Course", "Course")
                        .WithMany("Codes")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Course", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.CourseVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Droniverse.Academy.Domain.Entities.Drone", "Drone")
                        .WithMany()
                        .HasForeignKey("DroneID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Droniverse.Academy.Domain.Entities.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentVersion");

                    b.Navigation("Drone");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.CourseVersion", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Course", "Course")
                        .WithMany("CourseVersions")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Drone", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.DroneType", "DroneType")
                        .WithMany("Drones")
                        .HasForeignKey("DroneTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DroneType");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Droniverse.Academy.Domain.Entities.CourseVersion", "CourseVersion")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseVersionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CourseVersion");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.CourseVersion", "CourseVersion")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CourseVersionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseVersion");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Level", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Drone", "Drone")
                        .WithMany()
                        .HasForeignKey("DroneID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drone");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.LevelCourseRequirement", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Droniverse.Academy.Domain.Entities.Level", "Level")
                        .WithMany("LevelCourseRequirements")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Module", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.CourseVersion", "CourseVersion")
                        .WithMany("Modules")
                        .HasForeignKey("CourseVersionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseVersion");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.PrerequisiteCourse", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Droniverse.Academy.Domain.Entities.Course", "RequiredCourse")
                        .WithMany()
                        .HasForeignKey("PrerequisiteCourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("RequiredCourse");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.QuizAttempt", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.QuizQuestionAttempt", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.QuizAttempt", "QuizAttempt")
                        .WithMany("QuizQuestionAttempts")
                        .HasForeignKey("AttemptID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Droniverse.Academy.Domain.Entities.QuizQuestion", "QuizQuestion")
                        .WithMany("QuizQuestionAttempts")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuizAttempt");

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserAssignment", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Assignment", "Assignment")
                        .WithMany("UserAssignments")
                        .HasForeignKey("AssignmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Droniverse.Academy.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserCertificate", b =>
                {
                    b.HasOne("Certificate", "Certificate")
                        .WithMany("UserCertificates")
                        .HasForeignKey("CertificateID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserLab", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Lab", "Lab")
                        .WithMany("UserLabs")
                        .HasForeignKey("LabID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserLesson", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Lesson", "Lesson")
                        .WithMany("UserLessons")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserLevel", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Level", "Level")
                        .WithMany("UserLevels")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserModule", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Module", "Module")
                        .WithMany("UserModules")
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.UserSimulator", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.WebSimulator", b =>
                {
                    b.HasOne("Droniverse.Academy.Domain.Entities.Drone", "Drone")
                        .WithMany()
                        .HasForeignKey("DroneID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drone");
                });

            modelBuilder.Entity("Certificate", b =>
                {
                    b.Navigation("UserCertificates");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Course", b =>
                {
                    b.Navigation("Codes");

                    b.Navigation("CourseVersions");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.CourseVersion", b =>
                {
                    b.Navigation("Certificate");

                    b.Navigation("Enrollments");

                    b.Navigation("Feedbacks");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.DroneType", b =>
                {
                    b.Navigation("Drones");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Lab", b =>
                {
                    b.Navigation("UserLabs");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("UserLessons");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Level", b =>
                {
                    b.Navigation("LevelCourseRequirements");

                    b.Navigation("UserLevels");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Module", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("UserModules");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("QuizAttempts");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.QuizAttempt", b =>
                {
                    b.Navigation("QuizQuestionAttempts");
                });

            modelBuilder.Entity("Droniverse.Academy.Domain.Entities.QuizQuestion", b =>
                {
                    b.Navigation("QuizQuestionAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
