services:
  droniverse.gateway:
    image: droniverse.gateway
    build:
      context: .
      dockerfile: Droniverse.Gateway/Dockerfile
    ports:
    - "8888:8080"
    # environment:
    networks:
      - droniverse-network
  
  identity-microservice:
    image: identity-microservice:latest
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTP_ENVIRONMENT=Development
      - MYSQL_HOST=fstreak-mysql-fstreak.e.aivencloud.com
      - MYSQL_PORT=10556
      - MYSQL_DATABASE=IdentityDB
      - MYSQL_USER=avnadmin
      - MYSQL_PASSWORD=AVNS_-X0xwlWefp-g6mMhVdK

    ports:
    - "4000:9090"
    networks:
      - droniverse-network
networks:
  droniverse-network:
    driver: bridge
