<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Abstractions\" />
		<Folder Include="Config\" />
		<Folder Include="Middleware\" />
		<Folder Include="Templates\" />
		<EmbeddedResource Include="Templates/**/*.html" />
		<PackageReference Include="CloudinaryDotNet" Version="1.27.8" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="MySql.EntityFrameworkCore" Version="9.0.9" />
		<PackageReference Include="MailKit" Version="4.3.0" />
	</ItemGroup>

</Project>
