// <auto-generated />
using System;
using Droniverse.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Droniverse.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260420021600_Update_Foreign_Key_In_Table_SysPolicy")]
    partial class Update_Foreign_Key_In_Table_SysPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("char(36)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Account", null, t =>
                        {
                            t.HasCheckConstraint("CK_Account_Status", "`Status` IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RelatedEntityID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("NotificationID");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_created");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_status");

                    b.HasIndex("UserID")
                        .HasDatabaseName("idx_user");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_status_created");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PermissionID");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PermissionID")
                        .HasColumnType("char(36)");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.SysConfig", b =>
                {
                    b.Property<Guid>("SysConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("BufferEstimatedDuration")
                        .HasColumnType("int");

                    b.Property<string>("CertificateTemplateUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoCertificate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("SysConfigID");

                    b.ToTable("SysConfig", (string)null);
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.SysPolicy", b =>
                {
                    b.Property<Guid>("SysPolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("SysPolicyID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("SysPolicy", (string)null);
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.UserConfig", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.Property<byte>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("UserID");

                    b.ToTable("UserConfig", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserConfig_Language", "`Language` IN(0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.UserInfo", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<sbyte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("UserID");

                    b.ToTable("UserInfo", (string)null);
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.Account", b =>
                {
                    b.HasOne("Droniverse.Identity.Domain.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Droniverse.Identity.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Droniverse.Identity.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Droniverse.Identity.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.SysPolicy", b =>
                {
                    b.HasOne("Droniverse.Identity.Domain.Entities.Account", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Droniverse.Identity.Domain.Entities.Account", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.UserConfig", b =>
                {
                    b.HasOne("Droniverse.Identity.Domain.Entities.UserInfo", "UserInfo")
                        .WithOne("UserConfig")
                        .HasForeignKey("Droniverse.Identity.Domain.Entities.UserConfig", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.UserInfo", b =>
                {
                    b.HasOne("Droniverse.Identity.Domain.Entities.Account", "Account")
                        .WithOne("UserInfo")
                        .HasForeignKey("Droniverse.Identity.Domain.Entities.UserInfo", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.Account", b =>
                {
                    b.Navigation("UserInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.Role", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Droniverse.Identity.Domain.Entities.UserInfo", b =>
                {
                    b.Navigation("UserConfig")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
